### ISSUE TITLE
motic slide image sdk

### ISSUE THREAD

**Issue by yasohasakii** [sbalci/ParaPathology#2]
Hi, I'm wondering is there any tool for open motic slide format(*.mds) files by batch, then we can process them with OpenCV.etc. thanks.

**Comment by sbalci** [comment]
I think you may find better answers here: https://forum.image.sc
Also you may refer to:
- https://free.pathomation.com
- https://github.com/openslide/openslide/issues/228

**Comment by krushnavadan** [comment]
I need sample files, i have created own framework,
